### ISSUE TITLE
PMID:33510733    Pseudomonas aeruginosa Elastase Contributes to the Establishment of Chronic Lung Colonization and Modulates the Immune Response in a Murine Model

### ISSUE THREAD

**Issue by JonMWilkes** [PHI-base/curation#110] opened 2022-09-07 16:30 UTC
https://canto.phi-base.org/curs/28479d119040ef5d

@CuzickA I have been trying to put together a tier1 annotation for the above invited paper  – however I have been unable to locate PHI terms for acute and chronic infections. Is this specific to animal infections? I have populated the entry with the appropriate Uniprot ids, strain identifiers and pathogen geno/pheno-type entries, but I am unable to proceed to metagenotypes. How best to generate PHI terms associated with animal infections? 
<from Alayne>

Hi Jon,

I have looked at the session for the paper mentioned below. I noticed that in the pathogen phenotype conditions there is a new condition ‘delivery mechanism: cell free culture supernatent’. I think this condition would need to change to ‘liquid culture’ as the ‘delivery mechanism’ terms are defined as how the pathogen is delivered to the host. This annotation is for a pathogen only experiment.

 

In regards to your question below about ‘I have been unable to locate PHI terms for acute and chronic infections. Is this specific to animal infections?’. To annotate these types of experiments we need to identify the observed phenotypes. A few suggestions below.

For example Fig 2a. I have added in the ‘penetrance’ through the population Annotation Extension (AE), Fig # and text from paper into the comment section. Please go ahead and make the deltalasB inoculated onto mouse annotation. This can then be linked to the WT control using the ‘compared to control’ AE and the ‘infective ability’ AE ‘unaffected pathogenicity’.
 
For Fig 2b it looks like the observed phenotypes could be PHIPO term ‘stunted host growth during pathogen colonization’.
For Fig 2c at 2 dpi both WT and mutant could be PHIPO term ‘presence of pathogen growth within host’
For Fig 2 c,d at 7 dpi WT could be PHIPO term ‘presence of pathogen growth within host’, mutant could be PHIPO term ‘decreased pathogen growth within host’. (It’s not easy here to capture the host ‘clearing’ a higher quantity of the mutant that the WT.)

I don’t think that ‘acute and chronic infections’ are really suitable as PHIPO terms. They are more the conclusion of several observed phenotypes. Also we don’t really capture information on whether an infection is acute (develops suddenly and lasts a short time) or chronic (develops slowly and may worsen over an extended period of time). Multiple annotations at different time points may help us record this information if necessary. Please have another go following the suggestions above and let me know how you get on and whether you have any further questions. Your feedback on curating these animal pathogen publications is really useful as we have not curated so many of these papers yet. Many thanks.

Best wishes,
Alayne

**Comment by JonMWilkes** [comment] 2022-09-07 16:31
@CuzickA 
Thanks for these clarifications and suggestions. Sorry, I should have twigged that ‘delivery mechanism’  related to introduction of the pathogen. The upshot seems to be that we need some new (hopefully intuitive) PHIPO terms for animal/human systems. Your comments are very useful, and a good starting point for debating the issue of chronicity/persistence and questions of attenuation and long term changes in the severity of the disease state.

**Comment by CuzickA** [comment] 2022-09-09 10:16
Hi @JonMWilkes, just looking through this 

![image](https://user-images.githubusercontent.com/11753634/189327738-3f1ae648-c25b-495f-9e10-80a481ca929c.png)
I notice that there is only an annotation for the WT type here, shouldn't there also be an annotation for the pathogen mutant that I outlined in the comment above?

> For example Fig 2a. I have added in the ‘penetrance’ through the population Annotation Extension (AE), Fig # and text from paper into the comment section. Please go ahead and make the deltalasB inoculated onto mouse annotation. This can then be linked to the WT control using the ‘compared to control’ AE and the ‘infective ability’ AE ‘unaffected pathogenicity’.

**Comment by CuzickA** [comment] 2022-09-09 10:36
![image](https://user-images.githubusercontent.com/11753634/189328372-1637b9d2-26ef-47b4-9b08-b2044b5f61ea.png)

edits and reasons
![image](https://user-images.githubusercontent.com/11753634/189329814-81530ee3-3296-4daa-81b7-5efd4c2f79d0.png)
I have used the child PHIPO term to indicate 'presence', removed the 'CFU...' condition suggestion as this is not a condition but more expt evidence. I have changed the 'evidence' from 'other' to 'Macroscopic observation (quantitative observation)' as I am presuming they counted bacterial CFUs on plates with various dilutions - but I may be wrong here and 'particle size and count assay' or 'substance quantification' may be better??

All edits
![image](https://user-images.githubusercontent.com/11753634/189331365-0ab4d7ba-ef19-4fc4-b2cf-8115395b68d9.png)

**Comment by CuzickA** [comment] 2022-09-09 10:47
This the WT annotation, as above in Fig 2a , the mutant annotation is required.
![image](https://user-images.githubusercontent.com/11753634/189332770-deb3ca6c-3a73-43bd-a253-33e4a0d0d30f.png)



![image](https://user-images.githubusercontent.com/11753634/189333085-a7c5eba9-4f90-487d-987e-fbd0f3983b74.png)
edit to
![image](https://user-images.githubusercontent.com/11753634/189333427-823e9018-b27f-44c6-9638-3884301c1e40.png)

**Comment by CuzickA** [comment] 2022-09-09 10:53
![image](https://user-images.githubusercontent.com/11753634/189334023-27e900d8-7ae4-4623-9a74-ddee50b0d4fb.png)

Hi @JonMWilkes, please could you model this annotation on the ones we made for the PA DesB paper.
![image](https://user-images.githubusercontent.com/11753634/189334224-d66cd193-6b9e-4016-afe9-0fc78349a8aa.png)

You will need the WT and mutant metagnotype annotations and the UniProt IDs for the key cytokine/chemokine that you want to annotate.

**Comment by CuzickA** [comment] 2022-09-09 10:55
@JonMWilkes in summary please could you have another look at making the mutant annotations for Fig 2a and 3a and updating the annotation for Table 1. Many thanks.

**Comment by CuzickA** [comment] 2022-09-09 10:59
Quick question for @ValWood 
If we reassign a partially curated session to an author to complete, is it possible to reassign it back to ourselves in Admin mode if  they choose not to participate?

**Comment by ValWood** [comment] 2022-09-10 09:11
Yes, you can just "submit", and it will come into approval, then you will pick it up as "Admin" from there.

**Comment by JonMWilkes** [comment] 2022-09-12 10:29
Hi @CuzickA - just a quick query re. the Uniprot identifier to use in the case that an assayed protein is a heterodimer (in this case IL-12p70 - a dimer of P43431 and P43432). I cannot see how to attach more than one id to an assayed using extension.

**Comment by CuzickA** [comment] 2022-11-07 10:46
I have created NTR: abolished peptidase activity
so that we don't have a mixture of peptidase / catalytic activity terms in these annotations
![image](https://user-images.githubusercontent.com/11753634/200291669-da069f73-6f43-485d-b5dd-5b8ca3ee57cd.png)

**Comment by CuzickA** [comment] 2022-11-07 10:53
Looks like an extra annotation in the middle here - I am deleting this using the 'delete' option on the right hand side

![image](https://user-images.githubusercontent.com/11753634/200292763-1bfc421d-4048-4900-8efa-13de54df5200.png)

**Comment by CuzickA** [comment] 2022-11-07 13:53
> Hi @CuzickA - just a quick query re. the Uniprot identifier to use in the case that an assayed protein is a heterodimer (in this case IL-12p70 - a dimer of P43431 and P43432). I cannot see how to attach more than one id to an assayed using extension.

Hi, @JonMWilkes 
I don't think this can currently be captured in the annotation as there is only one slot to enter the 'assayed using' AE. For now I will make the annotation using P43431 and note P43432 in the comment. 
![image](https://user-images.githubusercontent.com/11753634/200326899-cae3ecf9-4330-4273-82a2-326792f57b89.png)

Just waiting for new PHIPO term to load and should be able to approve session tomorrow.

**Comment by CuzickA** [comment] 2022-11-08 10:10
See https://github.com/pombase/canto/issues/2658 for discussion on adding 'Assayed using with more than one gene or protein' using Amin mode 'edit as text' https://github.com/PHI-base/canto-docs/issues/25.

New PHIPO term now added.

Approving this session.

Next step - @JonMWilkes Please contact the author again with a follow up email, via the curation email account, explaining that we have undertaken a Tier 1 level curation of the paper. Please could the author review the curation at https://canto.phi-base.org/curs/28479d119040ef5d/ro/ and provide us with any feedback.

**Comment by CuzickA** [comment] 2023-01-13 14:53
Next step - @JonMWilkes Please contact the author again with a follow up email, via the curation email account, explaining that we have undertaken a Tier 1 level curation of the paper. Please could the author review the curation at https://canto.phi-base.org/curs/28479d119040ef5d/ro/ and provide us with any feedback.

**Comment by CuzickA** [comment] 2023-07-11 08:19
Some of these annotations have been flagged up in a search for pathogen phenotype WT allele with WT level expression.
![image](https://github.com/PHI-base/curation/assets/11753634/3ff40e29-58d9-4d03-9780-38a1f65c86ea)


These WT pathogen phenotype control annotations will need removing (as we don't curate single species controls) and possibly adding as GO MF annotations.

**Comment by CuzickA** [comment] 2023-07-11 08:28
![image](https://github.com/PHI-base/curation/assets/11753634/1dccee32-7eee-46a3-b9f2-23a356e77a98)

selected 'endopeptidase activity' as 'elastase activity' is a synonym

**Comment by CuzickA** [comment] 2023-07-11 08:29
Deleted
![image](https://github.com/PHI-base/curation/assets/11753634/467b9f55-5caa-46b6-b8b9-858ab3a2bf40)

**Comment by CuzickA** [comment] 2023-07-11 08:37
Also deleted
![image](https://github.com/PHI-base/curation/assets/11753634/adefc189-83f3-4b69-91b3-05ef6519ab3d)

This is tricky as the WT lasB from strain RP73 has no elastase activity. Therefore no shift in phenotype with deletion. A note has been made in the comment section but this is not displayed in PHI-base 5.

![image](https://github.com/PHI-base/curation/assets/11753634/89f55ba4-11e3-4c39-a3ee-242cc01abd08)

**Comment by CuzickA** [comment] 2023-07-11 08:38
Now looks like this

![image](https://github.com/PHI-base/curation/assets/11753634/b2b89897-4c3b-4ace-a6c2-256093c1cd74)
 
Session reapproved

**Comment by CuzickA** [comment] 2023-07-11 10:56
@ValWood I've been thinking about this tricky annotation further.

> Also deleted ![image](https://user-images.githubusercontent.com/11753634/252604270-adefc189-83f3-4b69-91b3-05ef6519ab3d.png)
> 
> This is tricky as the WT lasB from strain RP73 has no elastase activity. Therefore no shift in phenotype with deletion. A note has been made in the comment section but this is not displayed in PHI-base 5.
> 
> ![image](https://user-images.githubusercontent.com/11753634/252604786-89f55ba4-11e3-4c39-a3ee-242cc01abd08.png)

@ValWood I've been thinking about this tricky annotation further. What are your thoughts?

If I followed the curation method we are employing for the chemistry resistance curation then for lasBdelta strain RP73 should be annotated with 'normal pathogen peptidase activity'
Def: A single species molecular function phenotype in which the observed rate of a peptidase activity is normal (i.e. indistinguishable from wild type).

Both genotypes exhibit no lasB peptidase/elastase activity
WT lasB strain RP73
lasBdelta strain RP73

**Comment by ValWood** [comment] 2023-07-11 11:09
If the WT has no peptidase activity then is there any value in curating the peptidase  deletion phenotypes in relation to peptidase? What was the purpose of the experiments, that will probably provide the best clue how to curate them.

I would definitely make a "negated" GO annotation in this instance to capture that this strain has no "peptidase activity", but what did the authors expect from the deletion?

**Comment by CuzickA** [comment] 2023-07-11 11:21
Thanks. I've now also made the 'NOT' GO annotation. The difficulty is that we cannot record the strains in GO.
![image](https://github.com/PHI-base/curation/assets/11753634/a0ab845b-0994-47bd-95a0-d7867fe0f92e)


Strain RP45 and PAO1 do show lasB peptidase activity but strain RP73 does not.
There is a note in the comment section for lasB RP73 
'RP73 (isolated 7 years after RP45) showed no elastolytic activity, despite the presence of LasB protein being confirmed in cultures supernatants by Western blot. Since all three strains (PAO1, RP45, and RP73) have identical lasB sequences, the lack of activity in the RP73 variant is possibly due to incorrect processing of the mature protein.'

**Comment by CuzickA** [comment] 2023-07-11 11:59
> If the WT has no peptidase activity then is there any value in curating the peptidase deletion phenotypes in relation to peptidase? What was the purpose of the experiments, that will probably provide the best clue how to curate them.

From the abstract
![image](https://github.com/PHI-base/curation/assets/11753634/d335515b-ec91-4179-ae9b-e05c9d27cdf0)

I'm beginning to wonder whether it would be better to delete all the strain RP73 annotations (both pathogen phenotype and PHI phenotypes) and just focus on the strain RP45 annotations for the PHI phenotypes.
![image](https://github.com/PHI-base/curation/assets/11753634/09a1a408-917a-4af8-ae00-26d07a1c57bb)
 From the results
![image](https://github.com/PHI-base/curation/assets/11753634/a0bfe3df-50a7-4e14-a3a0-9c07e075992a)


@ValWood do you think it would make sense to remove the annotations for strain RP73?

Sometimes it is difficult to know which pieces of information are worth curating.

**Comment by ValWood** [comment] 2023-07-11 13:04
You are  correct it shouldn't have a negative GO annotation.

I guess the annotation is clear and could be useful.
There is no difference in infectivity between LasB WT and knockout which shows that, either LasB does not contribute, or is not active, so something can be inferred I guess.
It. implies a change in unidentified gene affecting LasB post-transcriptionally/translationally.

**Comment by CuzickA** [comment] 2023-07-11 13:19
ok, thanks @ValWood 

1) so i'll remove the negative GO annotation.

2) Leave the PHI annotations for strain RP73 LasB WT and knockout

3) What do I do about this pathogen phenotype annotation for strain RP73 LasB knockout
![image](https://github.com/PHI-base/curation/assets/11753634/d61abf35-bf45-4a54-9f02-5d93307b85e2)
leave as is or change it to 'normal...blah' as the both the WT and the knockout have no lasB peptidase/elastase activity?

**Comment by ValWood** [comment] 2023-07-11 13:21
I would remove that one...

**Comment by CuzickA** [comment] 2023-07-11 13:30
Thanks. Done and reapproved.

**Closed as completed by CuzickA** 2023-07-11 13:30 UTC
Labels: approved, Tier 1 curation, user feedback
