### ISSUE TITLE
  Problems loading Uniprot IDs into PhiBase5

### ISSUE THREAD

**Issue by JonMWilkes** [PHI-base/curation#109] opened 2022-08-26 13:28 UTC
@jseager7 @CuzickA 
I have identified a gene of interest in a study I want to annotate:
![uniprotSS01](https://user-images.githubusercontent.com/7281304/186910613-539f61a8-9238-4afd-b007-351b9c2bd81c.png)
However when I try to load this into the Gene List I get:
![phib5_01](https://user-images.githubusercontent.com/7281304/186910821-893555d8-35b4-44b5-9238-f04cd1bb25bc.png)
I have tried with a variety of ids for several proteins. Some already entered in other annotations are accepted, while novel ids seem to be rejected. 
Is there an issue with lookup to Uniprot? If I can't upload the genes is there a workaround to allow further annotation?

**Comment by jseager7** [comment] 2022-08-30 10:20
@JonMWilkes Thanks for flagging this up. This might be because UniProtKB has changed its API as part of its migration to the new website (possibly without warning its consumers), or because Canto's UniProtKB adapter is broken for some other reason.

I think the reason the existing UniProtKB IDs still work is because Canto caches data from UniProtKB to avoid having to look up data repeatedly, and the cache is probably kept indefinitely.

I'll open an issue on the upstream Canto repository since this will need to be fixed for all versions of Canto that use UniProt.

**Comment by jseager7** [comment] 2022-08-30 11:38
This problem should be fixed by https://github.com/pombase/canto/commit/7920bb611e62eb8c0a8dab903399c4c0bd1cc3ff.

I've updated the PHI-Canto server and confirmed that accession number A9QUN1 now loads as expected.

**Closed as completed by jseager7** 2022-08-30 11:38 UTC

**Comment by JonMWilkes** [comment] 2022-08-30 15:33
Hi @jseager7 - many thanks for this. I'll let you know how I get on.
