### ISSUE TITLE
PMID:32323095   The role of Pseudomonas aeruginosa DesB in pathogen-host interaction

### ISSUE THREAD

**Issue by JonMWilkes** [PHI-base/curation#107] opened 2022-05-24 13:36 UTC

**Comment by JonMWilkes** [comment] 2022-05-24 13:37
Initial curation completed and submitted to Phi-canto

**Comment by CuzickA** [comment] 2022-05-25 12:00
Thanks for creating this ticket @JonMWilkes 

Curation link: https://canto.phi-base.org/curs/9912dcabc045a08e/ro/

**Comment by CuzickA** [comment] 2022-05-25 14:04
Checking Curation of Fig 1
Current
![image](https://user-images.githubusercontent.com/11753634/170273821-aee2c6d3-2985-4753-9b6a-2c5058f1dd8f.png)
I have updated to 

![image](https://user-images.githubusercontent.com/11753634/170283257-b586ec29-7e59-4839-99b5-2f61a21c30b2.png)

Maybe this could also have AE 'assayed with' IL8 etc


Looks like these annotations are for Fig 2
![image](https://user-images.githubusercontent.com/11753634/170279744-c389eb65-7808-4f52-af7d-cd33b3a539d5.png)

I think these 'cell invasion assays' are the same as a penetration assay. Maybe 'cell invasion' could be added as a synonym to the PHIPO penetration terms.

I have deleted the 'conditions' that were entered as this information has already been captured with the evidence. Conditions are generally increased temp or adding a chemical.

@JonMWilkes and @ValWood, please let me know what you think about my edits.

**Comment by CuzickA** [comment] 2022-05-25 14:09
@jseager7 It looks like the PHIPO term 'infective ability phenotype' can be selected for annotation (see top screenshot above). This term is in do not annotate subsets. Please could you look into this. Thanks.

**Comment by jseager7** [comment] 2022-05-25 15:00
@CuzickA It isn't normally possible to annotate this term. Canto's default behaviour is to still show terms in the `qc_do_not_annotate` subset in the autocomplete, but not allow them to be annotated once selected. Here's what you see when you try to actually select the term:

![image](https://user-images.githubusercontent.com/37659591/170290516-43f04d60-1c04-4d3b-9e3e-250e0a247370.png)

As shown in the image, there's no option to continue.

The only way to bypass this check is to enter the _term ID_ instead of the term label into the text input, in which case Canto skips the check. I don't think this is a bug, but an intended workaround for expert curators in the (rare) case that the `qc_do_not_annotate` warning is wrong and should be ignored. This doesn't seem like one of those cases: usually the term suggestion feature should be used when there's no appropriate term.

- - -

If you want Canto to be stricter about this, I can add `qc_do_not_annotate` to the list of subsets that are ignored in the primary autocomplete, meaning they won't even appear to the user.

This might not be ideal though, since curators might start suggesting terms that exist in the ontology but are marked as do not annotate, because they'll have no way of ever seeing the terms and realising that it's redundant to make a term suggestion.

Also, even hiding terms from the autocomplete won't stop curators who enter term IDs. If we want to prevent that, then it will require new code changes and new configuration in Canto.

**Comment by CuzickA** [comment] 2022-05-27 08:15
Thanks for clarifying the above @jseager7.

@JonMWilkes please could you let us know 'how' you entered the term above 'infective ability phenotype'? Did you enter a term id or select the text from the dropdown menu? 

Jon, the reason I'm asking about this is that 'infective ability phenotype' is a grouping term for the infective ability AE terms e.g. 'reduced virulence' but should not be available as a primary PHIPO annotation term. Please let me know if you have any questions.

**Comment by CuzickA** [comment] 2022-05-27 08:53
Checking Figure 3
Original annotations
![image](https://user-images.githubusercontent.com/11753634/170661249-31943f09-3266-46bc-a55b-d5c5f13460f2.png)
Updated annotations
![image](https://user-images.githubusercontent.com/11753634/170665958-f788adba-c005-4a0e-b9c9-18d053facef2.png)


Hi @JonMWilkes, these types of annotations follow a two-step approach
1) primary PHIPO annotation e.g. 'survival of host organism with pathogen'
2) adding the AE 'infective ability' to record 'unaffected pathogenicity', 'reduced virulence' etc.

It should not be possible to select these 'infective ability' terms as primary PHIPO annotations (discussion above).

Please let me know if this two-step process makes sense to you and whether you think our help documentation needs to make this clearer?

**Comment by JonMWilkes** [comment] 2022-05-27 09:18
@CuzickA - I have not used any  term id in the annotation process and all selections have been made from drop downs menus. Hope this helps.

**Comment by CuzickA** [comment] 2022-05-27 09:24
> @CuzickA - I have not used any term id in the annotation process and all selections have been made from drop downs menus. Hope this helps.

Thanks for this info @JonMWilkes 

Are you able to provide a screenshot here in this ticket, where you are able to select e.g. 'reduced virulence' as a primary PHIPO annotation from a dropdown menu please

**Comment by CuzickA** [comment] 2022-05-27 09:31
Figure 4
Original annotations
![image](https://user-images.githubusercontent.com/11753634/170667841-923dfea6-1ff2-4157-8005-a1d9fb3e262e.png)
Updated annotations
![image](https://user-images.githubusercontent.com/11753634/170672211-aaa9717a-359c-429c-aaea-b24623764250.png)
We may need to make 2 lots of annotations here, one for amount of pathogen growth in host and one for tissue to tissue migration.

I will need to make a new PHI-ECO term for '11 hpi' and a new PHIPO term for 'decreased pathogen tissue to tissue migration within host'

**Comment by CuzickA** [comment] 2022-05-27 10:00
Table 2
Original annotations
![image](https://user-images.githubusercontent.com/11753634/170673706-5201b512-ccbd-4638-b96e-e038976fc20b.png)

Updated annotations
![image](https://user-images.githubusercontent.com/11753634/170677162-09ce97c8-beeb-4e52-b3f8-32cdf854be16.png)


Hi @ValWood, I'm really not sure about this one! How should we annotated an altered weight of a host organ? Do you think it falls under 'host morphology phenotype during pathogen invasion' or 'abnormal host structure induced by pathogen'?

**Comment by JonMWilkes** [comment] 2022-05-27 10:14
Hi @CuzickA,
Here is a dummy annotation I did where I selected a reduced virulence phentotype - you should be able to reproduce the selection from the history at the top (boxed)
![selectVir](https://user-images.githubusercontent.com/7281304/170680052-577f78f4-4420-4aa4-83ce-803b69bbdefc.png)

**Comment by CuzickA** [comment] 2022-05-27 10:21
Figure 5
Original annotations
![image](https://user-images.githubusercontent.com/11753634/170678526-5c100085-47e4-4b01-94d3-2689dc4ff3bd.png)

Updated to
![image](https://user-images.githubusercontent.com/11753634/170681275-9ffe3f3a-9185-4d75-92df-9e78e7c2b2e9.png)

@ValWood, what do you think of this way of annotating lung tissue inflammation?

_The WT should probably be ''inflammatory response present''._

**Comment by CuzickA** [comment] 2022-05-27 10:32
> Hi @CuzickA, Here is a dummy annotation I did where I selected a reduced virulence phentotype 

Hi @JonMWilkes, thanks for your screenshot above. I was able to reproduce your method and was also able to select 'reduced virulence' phenotype. 

@jseager7 it looks as if you cannot search for 'reduced virulence' directly, but if you search for parent term 'virulence phenotype' the child terms are available for selection. The same happens for 'pathogenicity phenotype', mutualism phenotype and the overall grouping term 'infective ability phenotype'. By drilling down the terms it is possible to select the children for annotation.

Hope that helps with fixing the problem :-)

**Comment by CuzickA** [comment] 2022-05-27 11:04
S Fig1
Original annotation
![image](https://user-images.githubusercontent.com/11753634/170686126-19f160b7-a219-47f3-94c2-9eec9427af52.png)

updated annotations
![image](https://user-images.githubusercontent.com/11753634/170687076-077ae7e6-4a20-4acc-9116-3896076b304b.png)

@ValWood, do you think this term 'death of host organism with pathogen' is suitable for cell cytotoxicity assays (pathogen being added to host cells)? Do we need a term at the 'cell' level or perhaps we could broaden the definition to include 'cell' as part of the individual organism?

**Comment by CuzickA** [comment] 2022-05-27 11:10
Regarding the strain for the desB mutant
![image](https://user-images.githubusercontent.com/11753634/170688051-d52f332a-6cbe-4c9b-b6f4-290f08c00b49.png)
![image](https://user-images.githubusercontent.com/11753634/170688328-9e34d78e-cfe5-4f87-8098-aec770531558.png)

It may be best to use 'PAO1' as this is what the desB mutant is being compared to and will be more informative to the PHI-base data users.

**Comment by CuzickA** [comment] 2022-05-27 11:14
![image](https://user-images.githubusercontent.com/11753634/170689052-23a999bc-51fc-4f83-9101-07f6418990f9.png)

I will delete the desB mutant entry highlighted in Green. We are aiming to just curate the 'disease' for the Wild type metagenotypes.

**Comment by CuzickA** [comment] 2022-05-27 11:36
I've finished checking through this session now. 

@JonMWilkes this has been a good curation session and a really useful exercise. Several issues have been identified, including the PHIPO infective term display, the 'two-step curation method', requirement for new PHIPO and PHI-ECO terms, and a few questions that I have for Val about the best way to curate some expt types.

**Comment by ValWood** [comment] 2022-05-27 14:01
> @ValWood, what do you think of this way of annotating lung tissue inflammation?

it isn't really a morphology phenotype.
I would be inclined to have a generic term "decreased inflammatory response". That would probably be enough, especially since you know the lung tissue is infected. 
I don't think you want a term for every tissue type.

For the "death of host organism" question. Don't you have a term for host cell death that you could use?

**Comment by ValWood** [comment] 2022-05-27 14:02
> I'm really not sure about this one! How should we annotated an altered weight of a host organ? Do you think it falls under 'host morphology phenotype during pathogen invasion' or 'abnormal host structure induced by pathogen'?

What is the intent of the experiment? Is it just to show increased pathogen load? Or something else?

**Comment by jseager7** [comment] 2022-06-06 08:50
> It looks as if you cannot search for 'reduced virulence' directly, but if you search for parent term 'virulence phenotype' the child terms are available for selection. The same happens for 'pathogenicity phenotype', mutualism phenotype and the overall grouping term 'infective ability phenotype'. By drilling down the terms it is possible to select the children for annotation.

@CuzickA What I'm more confused about is why, in my test session, it's not possible to see terms in the `qc_extension_only` subset, but it _is_ possible to see terms marked as `qc_do_not_annotate`.

Our configuration for these subsets is almost identical – in that `qc_extension_only` and `qc_do_not_annotate` are both meant to be ignored in the `primary_autocomplete` and `primary_select` configuration – the only difference is that `qc_do_not_annotate` is in the `do_not_annotate_subsets` configuration, while `qc_extension_only` isn't.

Since the current behaviour of `qc_extension_only` seems to be hiding the terms from the term selector entirely (and not just blocking them from being selected), it seems like a bug that the `qc_do_not_annotate` terms are being shown at all. I'm no longer sure what Canto's intended behaviour is, so I'll have to open an issue on the Canto repository.

**Comment by CuzickA** [comment] 2022-06-15 09:14
> > Hi @CuzickA, Here is a dummy annotation I did where I selected a reduced virulence phentotype
> 
> Hi @JonMWilkes, thanks for your screenshot above. I was able to reproduce your method and was also able to select 'reduced virulence' phenotype.
> 
> @jseager7 it looks as if you cannot search for 'reduced virulence' directly, but if you search for parent term 'virulence phenotype' the child terms are available for selection. The same happens for 'pathogenicity phenotype', mutualism phenotype and the overall grouping term 'infective ability phenotype'. By drilling down the terms it is possible to select the children for annotation.
> 
> Hope that helps with fixing the problem :-)

This has now been fixed. When I search for 'virulence phenotype', 'pathogenicity phenotype', 'mutualism phenotype' these terms are no longer available in the dropdown. 

I will hide above comments relevant to this now it has been resolved.

**Comment by CuzickA** [comment] 2022-06-15 09:25
> 



> It may be best to use 'PAO1' as this is what the desB mutant is being compared to and will be more informative to the PHI-base data users.

I have update the mutant strain to PAO1 and deleted the bespoke strain 13272

**Comment by CuzickA** [comment] 2022-06-15 11:52
Fig S1 above

> @ValWood, do you think this term 'death of host organism with pathogen' is suitable for cell cytotoxicity assays (pathogen being added to host cells)? Do we need a term at the 'cell' level or perhaps we could broaden the definition to include 'cell' as part of the individual organism?

> For the "death of host organism" question. Don't you have a term for host cell death that you could use?

@ValWood How about 'presence of pathogen-associated host lesions' ? Would this fit for cell cytoxicity?
![image](https://user-images.githubusercontent.com/11753634/173820693-9c2dcf9b-1d01-41ca-8508-bb501f751c6b.png)

def: 
![image](https://user-images.githubusercontent.com/11753634/173820341-1fd4cc0b-8ade-4a45-9d9f-0f23dda0bfad.png)

**Comment by CuzickA** [comment] 2022-06-15 13:20
Table 2


> > I'm really not sure about this one! How should we annotated an altered weight of a host organ? Do you think it falls under 'host morphology phenotype during pathogen invasion' or 'abnormal host structure induced by pathogen'?
> 
> What is the intent of the experiment? Is it just to show increased pathogen load? Or something else?


Build up of liquid/ swelling in host is greater with WT pathogen than with mutant.


![image](https://user-images.githubusercontent.com/11753634/173835321-20ab23e0-25cc-4bb4-aa4c-7ce3ef3dc1ad.png)
 
@ValWood Could this be curated with inflammation terms? maybe...
WT metagenotype 'inflammatory response present'
desB mutant metagenotype 'decreased inflammatory response'

**Comment by CuzickA** [comment] 2022-06-15 13:28
Figure 2 

> I think these 'cell invasion assays' are the same as a penetration assay. Maybe 'cell invasion' could be added as a synonym to the PHIPO penetration terms.

PHIPO looks like this 
![image](https://user-images.githubusercontent.com/11753634/173838166-d3e31e43-23a2-4642-9b26-c75d862789ec.png)

![image](https://user-images.githubusercontent.com/11753634/173838361-2a8ce338-07f3-4e3d-9a01-00204f9d76da.png)

@JonMWilkes and @ValWood do you think it would be worth adding 'invasion' as a synonym to these terms. I remember from discussion with Jon that 'penetration' may not have been clear enough on its own.

**Comment by ValWood** [comment] 2022-06-15 18:57
I think you could add as related, or broad (Invasion seems to cover more than just penetration- it could even be the life cycle stage.

**Comment by CuzickA** [comment] 2022-06-17 12:23
Hi @ValWood, I'm confused by which term I should use for cell cytotoxicity expt in FigS1.

WT and mutant Bacteria is added to human cell line to look for host cell death. A host cell viability assay with pathogen.

As far as I can see, we have the following PHI terms

at the organism level
![image](https://user-images.githubusercontent.com/11753634/174296182-87ed5419-58e3-40db-93d7-3e40e504890c.png)

term for pathogen-associated host lesions present
![image](https://user-images.githubusercontent.com/11753634/174296520-089e252a-7e60-4270-ba98-1e0a3caead36.png)


There are no relevant cell death terms under the PHI Cell phenotypes
![image](https://user-images.githubusercontent.com/11753634/174296843-591541c0-8b61-42d4-8f05-0772b205c7f7.png)
![image](https://user-images.githubusercontent.com/11753634/174297294-9b6cec6f-cd23-48e5-be14-fcbc279d4e31.png)


Which do you think is most suitable in this case?

**Comment by CuzickA** [comment] 2022-06-17 13:10
Need to add AE 'protein_assayed' to 'host defense-induced protein present' PHIPO:0001251 please @jseager7

**Comment by ValWood** [comment] 2022-06-20 08:40
I thought you had some host cell death terms?

**Comment by CuzickA** [comment] 2022-06-20 08:46
In the single species branch there is 'host cell death' but this is without a pathogen

![image](https://user-images.githubusercontent.com/11753634/174562285-bfb3e756-50e7-4d54-918e-fd7c5574a6cf.png)

and single specie 'cell viability'
![image](https://user-images.githubusercontent.com/11753634/174562536-d12c0bc6-a8fb-4939-a1ca-7a788b5525bb.png)

**Comment by jseager7** [comment] 2022-06-20 08:51
> Need to add AE 'protein_assayed' to 'host defense-induced protein present' PHIPO:0001251 please @jseager7

@CuzickA I've done this now, though it probably won't be visible until PHI-Canto is restarted.

**Comment by ValWood** [comment] 2022-06-20 09:10
I guess you could introduce a host cell viability with pathogen phenotype.
I worry  about the proliferation of phenotypes, but maybe you will need these are you annotate more human cell-based papers.

I was wondering why the single-species branch need to mention "host"? Why not just "cell death" if this isn't part of a pathogen-host interaction?

Maybe you do not want to curate every piece of supplementary information.  What is the author intent? If the author intent 
is to show that the immune system is affected perhaps these are the terms you would use ?

**Comment by CuzickA** [comment] 2022-06-20 09:21
![image](https://user-images.githubusercontent.com/11753634/174568798-46c3f4ee-7b9d-4c46-a903-7c35d188d461.png)

I will also need to curate similar expt for Fig 2 in
https://github.com/PHI-base/curation/issues/102

Yes, its this difficulty with cell, tissue, organism level that we've had in the past.

Do you think new 'host cell viability with pathogen phenotype' would fit under the organism level terms or PHI cell phenotypes?

![image](https://user-images.githubusercontent.com/11753634/174569556-44de5631-4292-49da-a013-728dd28d87c5.png)

![image](https://user-images.githubusercontent.com/11753634/174569841-6c766095-e033-4d94-81f4-1b58335ba28c.png)

**Comment by CuzickA** [comment] 2022-06-20 09:26
> I was wondering why the single-species branch need to mention "host"? Why not just "cell death" if this isn't part of a pathogen-host interaction?

I think we did this to indicate when a mutation in a pathogen results in a lethal/ inviable phenotype and in the host case, where a mutation activates the HR defense response causing cell death (without a pathogen being present). Do you think these need to merged?

**Comment by ValWood** [comment] 2022-06-20 12:55
I thought that  you were keeping pathogen/host out of the single-species branch, because that could be inferred from the context?

**Comment by CuzickA** [comment] 2022-06-20 13:10
Looking at some past tickets 

Might help with single species 'cell viability'
https://github.com/PHI-base/phipo/issues/298


Might help for the 'cell death terms' 
https://github.com/PHI-base/phipo/issues/306

**Comment by CuzickA** [comment] 2022-06-20 13:21
> I thought that you were keeping pathogen/host out of the single-species branch, because that could be inferred from the context?

Moving this single species discussion over to https://github.com/PHI-base/phipo/issues/298

**Comment by CuzickA** [comment] 2022-07-05 09:17
Added new terms, annotation for Fig S1 now looks like this
![image](https://user-images.githubusercontent.com/11753634/177294225-c6e22451-c57d-46e6-934e-82cb20958d1b.png)


This session has now been approved and I am closing the ticket.

**Comment by jseager7** [comment] 2022-11-22 14:07
@CuzickA There's an unused gene in this session: CXCL8 of _Homo sapiens_ ([UniProtKB:P10145](https://www.uniprot.org/uniprotkb/P10145/entry)) has been added but isn't annotated nor used in any assayed_using extensions.

I'm guessing CXCL8 was meant to be used in an assayed_using extension, since that's how the other human gene (IL6) has been used.

**Comment by jseager7** [comment] 2022-11-22 14:09
Note that unused genes will still be given their own gene page (and PHIG ID) in PHI-base 5 as it stands, so we should try to avoid this.

**Comment by CuzickA** [comment] 2022-11-22 14:13
@jseager7 Good spot. I will go into the session and recheck / delete it. Do we have any type of automated checking mechanism to prevent this happening again? I suppose its up to the person checking the curations but could be easy to miss.

**Comment by jseager7** [comment] 2022-11-22 14:18
There's no automated checking for this in PHI-Canto itself. We could add checks to the PHI-base 5 website to exclude genes with no annotations or usage in extensions, but the safest option is probably to add automated checks to the PHI-Canto JSON export to remove any gene objects that are unused.

**Comment by CuzickA** [comment] 2022-11-22 14:58
![image](https://user-images.githubusercontent.com/11753634/203346177-cedb6e6d-4e19-406c-962d-a8c95a19da45.png)
 I have just added the missing Fig1 assayed_using IL-8 annotations and reapproved session.

Automated checks would be useful.

**Comment by jseager7** [comment] 2022-11-22 14:59
> Automated checks would be useful.

I've added that to my to-do list.

**Closed as completed** 2022-11-22 15:07 UTC
Labels: approved
