### ISSUE TITLE
PMID:27644008 Characterisation of Ramularia collo-cygni laboratory mutants resistant to succinate dehydrogenase inhibitors

### ISSUE THREAD

**Issue by jingluodatacurator** [PHI-base/curation#193] opened 2023-07-20 22:28 UTC
Curated by @jingluodatacurator 

https://canto.phi-base.org/curs/46cc4ab2f530d7cf

**Comment by jingluodatacurator** [comment] 2023-07-21 10:53
Hi @CuzickA, I have curated 4 laboratory generated mutants (AA subst. by UV mutagenesis) resistant to boscalid (with highest severity of RF increase).
I'm not sure if I should also curate the mutants to all the other four fungicides?

**Comment by CuzickA** [comment] 2023-07-21 11:02
Hi @jingluodatacurator, were the other four fungicides mentioned in the abstract? As a general rule we are trying to report on the information from the title and abstract of the publication.

**Comment by jingluodatacurator** [comment] 2023-07-21 11:07
Hi @CuzickA, the title includes them all I think as it says '..mutants resistant to SDH Inhibitors'.

**Comment by CuzickA** [comment] 2023-07-21 11:10
Sounds like it might be useful to include them then please @jingluodatacurator

**Comment by CuzickA** [comment] 2023-09-26 13:44
It looks like this sessions needs a few more annotations once @jingluodatacurator has her email and GitHub access restored.

**Comment by CuzickA** [comment] 2023-09-27 14:06
tagging @jingluodatacurator

**Comment by jingluodatacurator** [comment] 2023-09-28 14:19
Hi @CuzickA, I have added all the other four fungicides (bixafen, isopyrazam, carboxin and fluopyram) for each mutant (Mutant 1, 11, 7 and 8) but not for Mutant 2 because.. (section 3.3 in the Result)

'Mut2, which had no detectable mutations in SdhB, C or D, showed a moderate level of resistance to isopyrazam (RF=31.55) and bixafen (RF=24.51). For the remaining three active ingredients, no differences in sensitivity were observed compared with the DK05 and the UK field population (boscalid RF=1.532, fluopyram RF=1.177, carboxin RF=2.752) (Table 4).'

Let me know if get this correct please.

**Comment by jingluodatacurator** [comment] 2023-09-28 14:20
Curation completed and pending review @CuzickA

**Comment by CuzickA** [comment] 2023-09-29 10:07
Used author given genbank ids to search for uniprots
'Full SdhB, SdhC and SdhD sequences can be found
in the GenBank database under the accession numbers KU758973,
KU758974 and KU758975 respectively'
SdhB https://www.uniprot.org/uniprotkb/A0A1S6KZ79/entry
SdhC https://www.uniprot.org/uniprotkb/A0A1S6KZ87/entry

Genotypes look good
![image](https://github.com/PHI-base/curation/assets/11753634/3cd74b5e-4377-4c9f-8f7e-2e9edd4aa437)

**Comment by CuzickA** [comment] 2023-09-29 10:17
![image](https://github.com/PHI-base/curation/assets/11753634/d8bcae48-d17c-4d41-a30e-3333f52c68cd)

This one should be 'normal growth on isopyrazam' if no differences were observed between mutant and wild type.

**Comment by CuzickA** [comment] 2023-09-29 10:26
Likewise, this one would also be 'normal growth on carboxin'
![image](https://github.com/PHI-base/curation/assets/11753634/0455fa7c-c881-4eed-bd94-348fe91a481d)

**Comment by CuzickA** [comment] 2023-09-29 11:00
Current Chemistry pathogen phenotypes now checked.

Next steps
1) new PHIPO terms (DONE 03_10_2023)
2) new PHI-ECO terms (DONE 03_10_2023)
3) add in AE alteration in archetype DONE see below

**Comment by CuzickA** [comment] 2023-09-29 11:16
Hi @jingluodatacurator, I think there are a few more annotations that could be made for this paper. These annotations would also help you become more familiar with making 'non-chemistry' annotations using PHI-Canto.

1) Pathogen phenotype
Maybe just the 14 dpi in vitro growth (without chemical)
![image](https://github.com/PHI-base/curation/assets/11753634/7fe4207e-ff86-4431-9493-f541c97c160f)
These are the current hyphal growth terms in PHIPO, we may to suggest a new term for 'increased rate of hyphae formation'
![image](https://github.com/PHI-base/curation/assets/11753634/a7fc1c7d-c173-42bf-87d9-83fdf6b62dca)

2) Pathogen host interaction phenotype
Need to make metagenotypes for the wild type and mutant pathogens inoculated onto barley (untreated with chemical).
Annotate with 'presence of pathogen-associated host lesions'. Same phenotype was seen with both wild type and mutant pathogen
![image](https://github.com/PHI-base/curation/assets/11753634/3194984d-08d7-49c5-86eb-ed1a0f50d4ce)

Please try to have a go at making these annotations and then we can discuss any issues :-)

**Comment by CuzickA** [comment] 2023-09-29 11:28
**AE alteration_in_archetype**

Ramularia collo-cygni

SdhB(aaS217L)[Not assayed] 'S228L; SdhB; PYRNTE'
SdhB(aaN224I)[Not assayed] 'N235I; SdhB; PYRNTE'
SdhC(aaH142R)[Not assayed] 'H134R; SdhC; PYRNTE'
SdhC(aaH142Q)[Not assayed] 'H134Q; SdhC; PYRNTE'

From Nichola's S file
![image](https://github.com/PHI-base/curation/assets/11753634/874d92f1-a929-4cd3-ac40-21684ac17f8f)
![image](https://github.com/PHI-base/curation/assets/11753634/a12fee7d-52cb-49f3-b518-f431971bbed2)
![image](https://github.com/PHI-base/curation/assets/11753634/d4afe309-3d28-4d19-8604-ce5a2a3401a8)
![image](https://github.com/PHI-base/curation/assets/11753634/75de64ba-69f3-4061-9df0-a2f6afbb7316)
![image](https://github.com/PHI-base/curation/assets/11753634/ac1a87fe-7133-403b-84ae-41c95a5594cd)

**Comment by CuzickA** [comment] 2023-09-29 11:46
**AE alteration_in_archetype**

Needs checking by Nichola.

Question: Target site name 'SdhB', 'SdhC' or 'SdhBCD'?
Maybe it is best keep them separate as Mair et al 2016 has three Sdh tables, one each for B, C and D.

NH (18_10_2023) Yes, keep these separate.

**Comment by jingluodatacurator** [comment] 2023-10-03 10:00
> Hi @jingluodatacurator, I think there are a few more annotations that could be made for this paper. These annotations would also help you become more familiar with making 'non-chemistry' annotations using PHI-Canto.
> 
> 1. Pathogen phenotype
>    Maybe just the 14 dpi in vitro growth (without chemical)
>    ![image](https://user-images.githubusercontent.com/11753634/271550037-7fe4207e-ff86-4431-9493-f541c97c160f.png)
>    These are the current hyphal growth terms in PHIPO, we may to suggest a new term for 'increased rate of hyphae formation'
>    ![image](https://user-images.githubusercontent.com/11753634/271552283-a7fc1c7d-c173-42bf-87d9-83fdf6b62dca.png)
> 2. Pathogen host interaction phenotype
>    Need to make metagenotypes for the wild type and mutant pathogens inoculated onto barley (untreated with chemical).
>    Annotate with 'presence of pathogen-associated host lesions'. Same phenotype was seen with both wild type and mutant pathogen
>    ![image](https://user-images.githubusercontent.com/11753634/271550297-3194984d-08d7-49c5-86eb-ed1a0f50d4ce.png)
> 
> Please try to have a go at making these annotations and then we can discuss any issues :-)

Thanks @CuzickA, I may need some help on these annotations. Maybe we could discuss it in tomorrow's meeting.

**Comment by jingluodatacurator** [comment] 2023-10-03 10:02
> **AE alteration_in_archetype**
> 
> Ramularia collo-cygni
> 
> SdhB(aaS217L)[Not assayed] 'S228L; SdhB; PYRNTE' SdhB(aaN224I)[Not assayed] 'N235I; SdhB; PYRNTE' SdhC(aaH142R)[Not assayed] 'H134R; SdhC; PYRNTE' SdhC(aaH142Q)[Not assayed] 'H134Q; SdhC; PYRNTE'
> 
> From Nichola's S file ![image](https://user-images.githubusercontent.com/11753634/271556717-874d92f1-a929-4cd3-ac40-21684ac17f8f.png) ![image](https://user-images.githubusercontent.com/11753634/271555883-a12fee7d-52cb-49f3-b518-f431971bbed2.png) ![image](https://user-images.githubusercontent.com/11753634/271556151-d4afe309-3d28-4d19-8604-ce5a2a3401a8.png) ![image](https://user-images.githubusercontent.com/11753634/271556393-75de64ba-69f3-4061-9df0-a2f6afbb7316.png) ![image](https://user-images.githubusercontent.com/11753634/271556574-ac1a87fe-7133-403b-84ae-41c95a5594cd.png)

Hi @CuzickA, I can't quite understand what you have done here. Maybe we could discuss it in tomorrow's meeting too, thanks.

**Comment by CuzickA** [comment] 2023-10-03 10:09
> > **AE alteration_in_archetype**
> > Ramularia collo-cygni
> > SdhB(aaS217L)[Not assayed] 'S228L; SdhB; PYRNTE' SdhB(aaN224I)[Not assayed] 'N235I; SdhB; PYRNTE' SdhC(aaH142R)[Not assayed] 'H134R; SdhC; PYRNTE' SdhC(aaH142Q)[Not assayed] 'H134Q; SdhC; PYRNTE'
> > From Nichola's S file ![image](https://user-images.githubusercontent.com/11753634/271556717-874d92f1-a929-4cd3-ac40-21684ac17f8f.png) ![image](https://user-images.githubusercontent.com/11753634/271555883-a12fee7d-52cb-49f3-b518-f431971bbed2.png) ![image](https://user-images.githubusercontent.com/11753634/271556151-d4afe309-3d28-4d19-8604-ce5a2a3401a8.png) ![image](https://user-images.githubusercontent.com/11753634/271556393-75de64ba-69f3-4061-9df0-a2f6afbb7316.png) ![image](https://user-images.githubusercontent.com/11753634/271556574-ac1a87fe-7133-403b-84ae-41c95a5594cd.png)
> 
> Hi @CuzickA, I can't quite understand what you have done here. Maybe we could discuss it in tomorrow's meeting too, thanks.

Hi @jingluodatacurator, this is information that I am adding in when I check the sessions. I have been working on this AE with Nichola. We are adding in the equivalent mutation position in the archetype species target site. Happy to discuss at tomorrow's meeting but for now I'll take care of making these entries and checking them through with Nichola.

**Comment by CuzickA** [comment] 2023-10-03 10:18
**Next steps**
1) Additional annotations to be made for pathogen only and PHI phenotypes. (Jing)
2) Check AE alteration in archetype with Nichola. (AC)

**Comment by CuzickA** [comment] 2023-10-03 10:22
> > Hi @jingluodatacurator, I think there are a few more annotations that could be made for this paper. These annotations would also help you become more familiar with making 'non-chemistry' annotations using PHI-Canto.
> > 
> > 1. Pathogen phenotype
> >    Maybe just the 14 dpi in vitro growth (without chemical)
> >    ![image](https://user-images.githubusercontent.com/11753634/271550037-7fe4207e-ff86-4431-9493-f541c97c160f.png)
> >    These are the current hyphal growth terms in PHIPO, we may to suggest a new term for 'increased rate of hyphae formation'
> >    ![image](https://user-images.githubusercontent.com/11753634/271552283-a7fc1c7d-c173-42bf-87d9-83fdf6b62dca.png)
> > 2. Pathogen host interaction phenotype
> >    Need to make metagenotypes for the wild type and mutant pathogens inoculated onto barley (untreated with chemical).
> >    Annotate with 'presence of pathogen-associated host lesions'. Same phenotype was seen with both wild type and mutant pathogen
> >    ![image](https://user-images.githubusercontent.com/11753634/271550297-3194984d-08d7-49c5-86eb-ed1a0f50d4ce.png)
> > 
> > Please try to have a go at making these annotations and then we can discuss any issues :-)
> 
> Thanks @CuzickA, I may need some help on these annotations. Maybe we could discuss it in tomorrow's meeting.

Hi @jingluodatacurator, I have reactivated the session so you should be able to go ahead and try adding in the new annotations. It would be great if you could have a go at this following the main PHI-Canto Help documentation and the Google FAQ document. We can then discuss any issues/sticking points when we meet tomorrow :-).

**Comment by jingluodatacurator** [comment] 2023-10-04 10:17
Hi @CuzickA, I'm not sure why I can't attach a snip image here?! I will email it to you now.

**Comment by CuzickA** [comment] 2023-10-09 12:39
New pathogen phenotype annotations look fine
![image](https://github.com/PHI-base/curation/assets/11753634/cb15412f-0a2e-47dd-845a-133a3402e91c)

**Comment by CuzickA** [comment] 2023-10-09 12:41
New PHI annotations

![image](https://github.com/PHI-base/curation/assets/11753634/ef28a2bd-c170-488a-8c0f-e47da6222824)

**Comment by CuzickA** [comment] 2023-10-09 13:07
Feedback on PHI annotations for @jingluodatacurator 

1) The two metagenotypes with the altered pathogen inoculated onto the wild type host look pretty good. The wild type host 'H. vulgare' needs to have the strain/cultivar name added.
From the text section 2.4 this is 'Optic'
![image](https://github.com/PHI-base/curation/assets/11753634/be2380cf-4de7-4877-9b80-736b545d3a99)
In this section, add 'optic' instead of 'wild type'
![image](https://github.com/PHI-base/curation/assets/11753634/b1b952ea-2e28-4445-9d5c-1871a0ed8db6)
![image](https://github.com/PHI-base/curation/assets/11753634/b11f713e-19ca-4172-b565-f8264c98a19c)

I have now made these changes with 'optic' as the wild type host strain/cultivar

2) For metagenotypes we also need to make a wild type control metagenotype, please see the help documentation https://canto.phi-base.org/docs/genotypes#metagenotype_management section 'Creating control metagenotypes'.
Here is an example for SdhB
![image](https://github.com/PHI-base/curation/assets/11753634/ca4f0a75-45e8-42e7-802e-ea66bacdae61)

Jing, please have a go at creating the wild type control metagenotype for SdhC

**Comment by CuzickA** [comment] 2023-10-09 13:31
Feedback continued for @jingluodatacurator 

3. For the annotations here, we want to curate the pathogen inoculation onto host information without the chemistry.

Text from section 3.4.4.
'Disease symptoms, initial pepper-like spots expanding
to small, brown-to-blackish necrotic lesions, on the untreated
leaf segments were observed macroscopically from 25 DPI for all
three isolates used in this study (data not shown). This showed that
Mut11 and Mut7 could infect the host plant barley, reproduce successfully
by generating spores and complete their life cycle, further
suggesting that there was no measurable fitness penalty associated
with the target mutations conferring resistance to SDHIs.'

Note: this data is not shown, so we would remove 'Figure 4' and add 'Text p. 1192' to the 'Figure column'
From this text, I understand that the wild type and two pathogen mutants showed the same lesions in the host.
Therefore I would add the PHIPO term 'presence of pathogen-associated host lesions'
![image](https://github.com/PHI-base/curation/assets/11753634/14c02929-693b-4b47-a3f4-60a16c06d3bc)
![image](https://github.com/PHI-base/curation/assets/11753634/54438567-3b9d-40f1-bb68-0fb1e9761fa2)

4. I have also changed the evidence code from 'other' to 'Macroscopic observation (qualitative observation)' as these lesions would be visible by eye.

@jingluodatacurator, please could you add/edit the PHIPO terms for the wild type and mutant SdhC inoculated onto barley (metagenotypes from 2 above).

The next set of comments with focus on the conditions and AEs.

**Comment by CuzickA** [comment] 2023-10-09 13:45
5. Notes on conditions @jingluodatacurator 
![image](https://github.com/PHI-base/curation/assets/11753634/dd999105-af8a-454f-bad7-fc90a0a46fd3)
i) We don't need to add 'leaf assay' here as this is not really a condition. A condition is adding a chemical, temperature etc. The AE infects tissue record the information about the 'leaf'
ii) The text in the publication states that the disease symptoms were observed '25 dpi'. Therefore, I am changing '1 day post inoculation' to '25 days post inoculation' (note: the text is red as I will need to make a new ontology term)
iii) Removing chemical
iv) Also changed the light conditions to 'intermittent light' as seemed a better match (12 h light, 12 h dark cycles)

Now looks like this
![image](https://github.com/PHI-base/curation/assets/11753634/084dc6aa-a251-4cfd-817d-088428dcec99)

**Comment by CuzickA** [comment] 2023-10-09 13:52
6. notes on AEs for @jingluodatacurator 
i) Removing AEs severity and penetrance as not applicable.
ii) For the mutant pathogen inoculated onto the wild type host we want to use the AE 'compared to'. We then add the corresponding wild type metagenotype. We can then add the AE infective ability 'unaffected pathogenicity' to the mutant metagenotype annotation as the wild type metagenotype and the mutant pathogen metagenotype have the same phenotype.
This is what it wold look like
![image](https://github.com/PHI-base/curation/assets/11753634/ff3bc4f2-2cd5-41d3-95b2-e955f24dd3a4)
![image](https://github.com/PHI-base/curation/assets/11753634/8ba01716-6299-4612-8813-1777b4862d6b)

**Comment by CuzickA** [comment] 2023-10-09 13:57
Session reactivated for @jingluodatacurator to make further changes.

In summary, read through above comments on the edits that I have made. Create the wild type metagenotype control for SdhC and make relevant annotations.

Please let me know if you have any follow up questions as I realise there is a lot to take on board here.

**Comment by CuzickA** [comment] 2023-10-09 13:59
Note to self
1) Add host strain to list
2) Create new PHI-ECO term for '25 dpi'
3) Create new PHIPO term

**Comment by jingluodatacurator** [comment] 2023-10-10 10:31
> Feedback on PHI annotations for @jingluodatacurator
> 
> 1. The two metagenotypes with the altered pathogen inoculated onto the wild type host look pretty good. The wild type host 'H. vulgare' needs to have the strain/cultivar name added.
>    From the text section 2.4 this is 'Optic'
>    ![image](https://user-images.githubusercontent.com/11753634/273591984-be2380cf-4de7-4877-9b80-736b545d3a99.png)
>    In this section, add 'optic' instead of 'wild type'
>    ![image](https://user-images.githubusercontent.com/11753634/273592316-b1b952ea-2e28-4445-9d5c-1871a0ed8db6.png)
>    ![image](https://user-images.githubusercontent.com/11753634/273593429-b11f713e-19ca-4172-b565-f8264c98a19c.png)
> 
> I have now made these changes with 'optic' as the wild type host strain/cultivar
> 
> 2. For metagenotypes we also need to make a wild type control metagenotype, please see the help documentation https://canto.phi-base.org/docs/genotypes#metagenotype_management section 'Creating control metagenotypes'.
>    Here is an example for SdhB
>    ![image](https://user-images.githubusercontent.com/11753634/273593133-ca4f0a75-45e8-42e7-802e-ea66bacdae61.png)
> 
> Jing, please have a go at creating the wild type control metagenotype for SdhC

Hi @CuzickA, please check the wild type control metagenotype for SdhC been created, link below thanks.

https://canto.phi-base.org/curs/46cc4ab2f530d7cf

**Comment by CuzickA** [comment] 2023-10-10 10:36
Hi @jingluodatacurator,

yes, this looks good for the wild type control metagenotype for SdhC

![image](https://github.com/PHI-base/curation/assets/11753634/ba3b3109-5981-4e9d-b496-4dce0b613034)

Next steps, edit the PHIPO terms and AEs

**Comment by jingluodatacurator** [comment] 2023-10-10 11:00
> Hi @jingluodatacurator,
> 
> yes, this looks good for the wild type control metagenotype for SdhC
> 
> ![image](https://user-images.githubusercontent.com/11753634/273868981-ba3b3109-5981-4e9d-b496-4dce0b613034.png)
> 
> Next steps, edit the PHIPO terms and AEs

Hi @CuzickA, PHIPO terms and AEs have been edited, please check on the link below thanks.

https://canto.phi-base.org/curs/46cc4ab2f530d7cf#

**Comment by CuzickA** [comment] 2023-10-10 11:09
Hi @jingluodatacurator, these look great

![image](https://github.com/PHI-base/curation/assets/11753634/f3f1ba65-0eb5-405d-8efc-66db7c4530db)
![image](https://github.com/PHI-base/curation/assets/11753634/9c58e197-0d4b-4343-b128-d978408a7bd2)

**Comment by CuzickA** [comment] 2023-10-10 11:36
> Note to self
> 
> 1. Add host strain to list
> 2. Create new PHI-ECO term for '25 dpi'
> 3. Create new PHIPO term

Above all done, just waiting for loading into PHI-Canto.
After this need AE archetype checking by Nichola and then session will be ready to approve.

**Comment by CuzickA** [comment] 2023-10-11 08:12
Terms now loaded into PHI-Canto.

 Need AE archetype checking by Nichola and then session will be ready to approve.

**Comment by CuzickA** [comment] 2023-10-18 10:45
AE archetype checked by Nichola and looks fine. Approving session and closing ticket.

**Closed as completed by CuzickA** 2023-10-18 10:45 UTC
Labels: approved, chemistry, e.g. AE alteration in archetype, new strain, archetype checked, SdhB/C/D target site
