### ISSUE TITLE
Decide when to use 'diploid mode'

### ISSUE THREAD

**Issue by CuzickA** [PHI-base/curation#169] opened 2023-07-05 13:51 UTC
We have recently enabled diploid mode in PHI-Canto and used it to curate a Chemistry paper #127

It would be good to write up some rules and examples of when to use this in our FAQ documentation.

A few points to consider
1) Are we only going to use this option in the pathogen genotypes for chemistry curation? Would we also use it for any other Pathogen phenotypes or PHI phenotypes associated with the paper?
2) If a diploid pathogen is used in an expt but the authors only report on homozygous genotypes do we use the haploid or diploid option?
3) Do we want to extend this option to the host genotypes? The diploid option is currently enabled for host genotypes. This could get really complicated with the different ploidy of different host species.

@ValWood is there currently any guidance on using 'diploid mode'?
@MPiovesana, please go ahead and start thinking about this some more for drafting text in the FAQ document.

**Comment by ValWood** [comment] 2023-07-05 14:26
The 'diploid' mode is covered in our docs
https://curation.pombase.org/pombe/docs/fypo_annotation#multi-allele-phenotypes
but we don't have any specific curation examples (we presume users will know if they need to sue it).

This was only added fairly recently, 
This was the new item:
https://www.pombase.org/news
New diploid genotype & phenotype display
2021-04-29

PomBase now includes pages for curated diploid genotypes, and displays phenotypes annotated to them on gene and publication pages. For more details see the documentation for [phenotype annotations](https://www.pombase.org/documentation/gene-page-phenotypes) and [genotype pages](https://www.pombase.org/documentation/genotype-page).

**Comment by MPiovesana** [comment] 2023-07-07 14:24
@CuzickA Whilst playing around with the Create Diploid Locus function, I noticed a few things which I would like to make the team aware of:

If the curator wishes to create a heterozygous diploid genotype including one altered allele and one wild type allele, and starts the process by selecting the altered genotype, the window below is shown:

<img width="490" alt="image" src="https://github.com/PHI-base/curation/assets/134392805/13bf1f44-f253-422b-97d8-4bf5012c90bf">

Despite the second option being "altered allele / wild type", it is seemingly not possible to select this option here; I say this as every time I tried, the first option remains selected, and cannot be unselected (as shown below). If the button OK is pressed, only a homozygous mutant genotype is created under Diploid genotypes.

<img width="467" alt="image" src="https://github.com/PHI-base/curation/assets/134392805/ee74efcc-bd54-4bf3-8a9e-c7b27117a3c0">

So, in order to create a heterozygous genotype "altered allele + wild type", the user must first create a wild type allele of the gene in question, and then start the create diploid locus process by selecting this allele. By doing so, the window below is shown:

<img width="481" alt="image" src="https://github.com/PHI-base/curation/assets/134392805/49863d52-09ae-4b2d-8d63-df4a1e97a00e">

Here, by selecting the second option, the curator can select which altered allele he would like to include in this heterozygous, diploid genotype.

<img width="475" alt="image" src="https://github.com/PHI-base/curation/assets/134392805/ddcc9e07-e9cb-4077-bbc3-b9750e83d3eb">

@jseager7 is this a glitch in the system, or has this been designed specifically to ensure that users first create a wild type allele? Even after the creation of the wild type allele, I found that I cannot create the heterozygous mutant/wt genotype if I start by selecting the mutant allele. @CuzickA would you be able to try this out as well, perhaps, to see if the issue is happening consistently?

**Comment by jseager7** [comment] 2023-07-10 09:00
@MPiovesana Thanks for testing this. It already looks like a glitch that two of the options can be selected at once, since the radio buttons (the circular selection icons) are meant to prevent that.

Diploid mode has so far only been tested on single-species versions of Canto, so there are likely to be some glitches when using it with multi-species mode. I didn't have time to test diploid creation in multi-species mode before enabling it, but I'll look into this now.

**Comment by jseager7** [comment] 2023-07-10 13:12
I've opened an issue about these glitches on the main Canto issue tracker (linked above). There's definitely some strange behaviour happening but I don't know enough about this part of the code to fix it yet.

**Comment by jseager7** [comment] 2023-07-11 09:27
The developers of PomBase have found a fix for this glitch, but I'm just waiting for confirmation from PomBase on whether the order that the alleles appear in the diploid has any biological meaning (i.e. whether the order of the alleles corresponds to the order of the chromosomes). Currently, the order of alleles that is shown in the diploid creation popup does not match the order of alleles when the diploid is created.

**Comment by CuzickA** [comment] 2023-07-12 08:56
> @CuzickA would you be able to try this out as well, perhaps, to see if the issue is happening consistently?

I see the same bugs as reported above.

**Comment by jseager7** [comment] 2023-07-12 09:31
I've tested the fix on the PHI-Canto test server and everything seems fine. I'll deploy the changes on the main PHI-Canto server tonight.

**Comment by jseager7** [comment] 2023-07-13 10:31
The changes have been deployed now so the glitch with creating diploids should be fixed. I'm going to hide this and the previous comments as resolved.

**Comment by MPiovesana** [comment] 2023-07-13 14:13
> The changes have been deployed now so the glitch with creating diploids should be fixed. I'm going to hide this and the previous comments as resolved.

@jseager7 @CuzickA I have briefly tested the 'Create diploid locus' function this afternoon and the glitch has indeed been resolved. Now it is possible to create a heterozygous genotype (mutant allele / wt allele) by selecting the mutant genotype, clicking on 'Created diploid locus', and selecting the option which includes mutant and wt allele. It no longer seems to be necessary to create a wt allele in order to create a diploid heterozygous genotype. Thank you for sorting this out!

**Comment by CuzickA** [comment] 2023-07-14 08:09
Thanks @jseager7 
Do you foresee any problems displaying these diploid genotypes on the new PHI-base 5 display?

**Comment by CuzickA** [comment] 2023-07-14 08:47
Current examples of sessions using diploid mode.  
https://github.com/PHI-base/curation/issues/116
https://github.com/PHI-base/curation/issues/127

Both are for Candida albicans

**Comment by jseager7** [comment] 2023-07-17 09:03
> Do you foresee any problems displaying these diploid genotypes on the new PHI-base 5 display?

They probably won't display correctly. We'll have to discuss this at the next meeting.

**Comment by CuzickA** [comment] 2024-02-07 09:40
I am checking another session using diploid mode https://github.com/PHI-base/curation/issues/188

@jseager7, did we decide whether these could be displayed in PHI5 or whether this would be a future add on to PHI5 after the initial launch?

**Comment by jseager7** [comment] 2024-02-07 09:51
I don't think that the PHI-base 5 website currently supports diploid mode and adding support for displaying it on the website would probably require further funding. Unless there's some kind of workaround we can use in the allele name. I'd have to check how PomBase display diploids on their website.

**Comment by ValWood** [comment] 2024-02-07 09:53
For a lonf time we reported diploid status in the background field. It's quite a lot of work to change display etc   if you don't have many diploids to annotate.

**Comment by jseager7** [comment] 2024-02-07 09:55
We can display the background on our website so that would be a useful workaround, thanks.

**Comment by CuzickA** [comment] 2024-09-06 14:18
> We can display the background on our website so that would be a useful workaround, thanks.

Hi @jseager7, did the diploid display get resolved in the end? Can we close this ticket?

**Comment by jseager7** [comment] 2024-09-09 08:49
We haven't had a chance to test how this works on the website because we haven't made any further releases. I'd need to change the release pipeline to include diploid information in the background as a workaround. Those tasks belong in other trackers though, so I'll close this issue.

**Closed as completed by jseager7** 2024-09-09 08:49 UTC
