### ISSUE TITLE
PMID:17379549 MgAtr7, a new type of ABC transporter from Mycosphaerella  graminicola involved in iron homeostasis

### ISSUE THREAD

**Issue by jingluodatacurator** [PHI-base/curation#202] opened 2023-10-18 10:25 UTC
Curated by @jingluodatacurator 

https://canto.phi-base.org/curs/e06ded1cb28d669c

Notes:
Uniprot ID: P41388
Strain: IPO323
Main expt. for curation: see Materials and Methods 2.3 & 2.4, Results 3.3 & 3.4

AC: UniProt entered into session is F9XJ73 (not P41388 as listed above).

**Comment by CuzickA** [comment] 2023-10-30 10:00
Hi @jingluodatacurator, please could you email me the highlighted PDF so that I can check the session once you have curated it.

**Comment by CuzickA** [comment] 2023-10-30 10:02
Current annotations

![image](https://github.com/PHI-base/curation/assets/11753634/5ee30061-3aa9-4e2c-8eec-f1a977f6a69c)

@jingluodatacurator, which chemical is the altered pathogen more sensitive to?

**Comment by jingluodatacurator** [comment] 2023-11-01 11:46
> Current annotations
> 
> ![image](https://user-images.githubusercontent.com/11753634/279013214-5ee30061-3aa9-4e2c-8eec-f1a977f6a69c.png)
> 
> @jingluodatacurator, which chemical is the altered pathogen more sensitive to?

Hi @CuzickA, I'm not quite sure if the article mentioned the chemicals. Could you take a look at Results 3.4 please and let me know? Thanks.

**Comment by CuzickA** [comment] 2023-11-01 12:25
> Hi @jingluodatacurator, please could you email me the highlighted PDF so that I can check the session once you have curated it.

Thanks for sending this through @jingluodatacurator

**Comment by CuzickA** [comment] 2023-11-01 12:28
> > Current annotations
> > ![image](https://user-images.githubusercontent.com/11753634/279013214-5ee30061-3aa9-4e2c-8eec-f1a977f6a69c.png)
> > @jingluodatacurator, which chemical is the altered pathogen more sensitive to?
> 
> Hi @CuzickA, I'm not quite sure if the article mentioned the chemicals. Could you take a look at Results 3.4 please and let me know? Thanks.

@jingluodatacurator, In Results 3.4 the following text
![image](https://github.com/PHI-base/curation/assets/11753634/65a610b9-e5c2-4285-800d-f4903de733e6)

Suggests that no increase in sensitivity was found for the tested compounds in section 2.

**Comment by CuzickA** [comment] 2023-11-01 12:33
@jingluodatacurator 

Figure 5 is to do with iron sensitivity which could be curated.

**Comment by jingluodatacurator** [comment] 2023-11-01 12:35
> > > Current annotations
> > > ![image](https://user-images.githubusercontent.com/11753634/279013214-5ee30061-3aa9-4e2c-8eec-f1a977f6a69c.png)
> > > @jingluodatacurator, which chemical is the altered pathogen more sensitive to?
> > 
> > 
> > Hi @CuzickA, I'm not quite sure if the article mentioned the chemicals. Could you take a look at Results 3.4 please and let me know? Thanks.
> 
> @jingluodatacurator, In Results 3.4 the following text ![image](https://user-images.githubusercontent.com/11753634/279673170-65a610b9-e5c2-4285-800d-f4903de733e6.png)
> 
> Suggests that no increase in sensitivity was found for the tested compounds in section 2.

Hi @CuzickA, I cannot find section 2 though, could you point please?

**Comment by CuzickA** [comment] 2023-11-01 12:41
Hi @jingluodatacurator, looks like its in the Methods '2.5. Sensitivity assays'.

**Comment by CuzickA** [comment] 2023-11-01 15:24
Hi @jingluodatacurator, I think that you could also curate PHI phenotypes here

![image](https://github.com/PHI-base/curation/assets/11753634/ca34faeb-dd68-44be-bdd2-4d3bf2cdce1c)
![image](https://github.com/PHI-base/curation/assets/11753634/4c68fbbb-917f-4081-b5d8-be9f607821dd)


Might need to look up paper referenced in text below to find out which PHI phenotype you would make the annotations to eg is disease observed by host lesions??
![image](https://github.com/PHI-base/curation/assets/11753634/d880affb-d873-459e-bc6c-b9ba2bc381f2)

**Comment by jingluodatacurator** [comment] 2023-11-02 11:31
> @jingluodatacurator
> 
> Figure 5 is to do with iron sensitivity which could be curated.

Hi @CuzickA, I have curated iron sensitivity of mutants, please check thanks.

**Comment by jingluodatacurator** [comment] 2023-11-02 11:32
> Hi @jingluodatacurator, I think that you could also curate PHI phenotypes here
> 
> ![image](https://user-images.githubusercontent.com/11753634/279717392-ca34faeb-dd68-44be-bdd2-4d3bf2cdce1c.png) ![image](https://user-images.githubusercontent.com/11753634/279717428-4c68fbbb-917f-4081-b5d8-be9f607821dd.png)
> 
> Might need to look up paper referenced in text below to find out which PHI phenotype you would make the annotations to eg is disease observed by host lesions?? ![image](https://user-images.githubusercontent.com/11753634/279718133-d880affb-d873-459e-bc6c-b9ba2bc381f2.png)

Hi @CuzickA, can we please discuss this curation bit in our meeting next Tuesday thanks.

**Comment by jingluodatacurator** [comment] 2023-11-07 14:27
> Hi @jingluodatacurator, I think that you could also curate PHI phenotypes here
> 
> ![image](https://user-images.githubusercontent.com/11753634/279717392-ca34faeb-dd68-44be-bdd2-4d3bf2cdce1c.png) ![image](https://user-images.githubusercontent.com/11753634/279717428-4c68fbbb-917f-4081-b5d8-be9f607821dd.png)
> 
> Might need to look up paper referenced in text below to find out which PHI phenotype you would make the annotations to eg is disease observed by host lesions?? ![image](https://user-images.githubusercontent.com/11753634/279718133-d880affb-d873-459e-bc6c-b9ba2bc381f2.png)

Hi @CuzickA, PHI phenotypes have been added, need checking thanks.

**Comment by CuzickA** [comment] 2023-11-08 08:43
@jingluodatacurator, thank you for making the extra annotations. I will try to check them soon :-).

**Comment by CuzickA** [comment] 2023-11-08 09:18
Hi @jingluodatacurator, I had a quick look at this. You have made a great start, well done. A couple of things to improve the PHI phenotype annotations please
1) We need to curate the wild type controls for the pathogen-host interactions. We also did this in ticket https://github.com/PHI-base/curation/issues/193
2) Once the wild type controls are curated this metagenotype can be added to the AE for compared to control (instead of the mutant metagenotype currently added).
3) The PHIPO terms that have been selected are slightly different - was this intentional? They have different meanings. 'presence of pathogen-associated host defense induced lesions' is when there is evidence that the lesion in the host is caused by a host defence response. 'presence of pathogen-associated host lesions' is used when we don't know from the publication whether the lesions in the host are caused by a pathogen substance or whether the host has mounted a defense response to the pathogen which results in lesions.

![image](https://github.com/PHI-base/curation/assets/11753634/0608d553-6f6e-4522-92b2-667b19a60c65)


Note to self: I still need to check the rest of this session.

**Comment by jingluodatacurator** [comment] 2023-11-09 10:45
> Hi @jingluodatacurator, I had a quick look at this. You have made a great start, well done. A couple of things to improve the PHI phenotype annotations please
> 
> 1. We need to curate the wild type controls for the pathogen-host interactions. We also did this in ticket [PMID:27644008 Characterisation of Ramularia collo-cygni laboratory mutants resistant to succinate dehydrogenase inhibitors #193](https://github.com/PHI-base/curation/issues/193)
> 2. Once the wild type controls are curated this metagenotype can be added to the AE for compared to control (instead of the mutant metagenotype currently added).
> 3. The PHIPO terms that have been selected are slightly different - was this intentional? They have different meanings. 'presence of pathogen-associated host defense induced lesions' is when there is evidence that the lesion in the host is caused by a host defence response. 'presence of pathogen-associated host lesions' is used when we don't know from the publication whether the lesions in the host are caused by a pathogen substance or whether the host has mounted a defense response to the pathogen which results in lesions.
> 
> ![image](https://user-images.githubusercontent.com/11753634/281338511-0608d553-6f6e-4522-92b2-667b19a60c65.png)
> 
> Note to self: I still need to check the rest of this session.

Hi @CuzickA, for 1 and 2 above, I thought I have curated the wild type controls?! For 3, I'm not sure if I have understood the terms correctly, now I have thanks. Maybe we could have a quick chat on teams next week to discuss all 3.

**Comment by CuzickA** [comment] 2023-11-13 10:31
Hi @jingluodatacurator, for the metagenotype wild type controls we need to combine a wild type pathogen genotype with the wild type host genotype. We did this in ticket #193, here is a screenshot from the comment dated 9 Oct
![image](https://github.com/PHI-base/curation/assets/11753634/4d9e1cde-6dbf-4896-9cc6-8b0bc16a9765)

So for this session PMID:17379549 we would need a wild type pathogen genotype for MgAtr7 combined with wild type T. aestivum to create the wild type control metagenotype.

Happy to have a short Teams chat to discuss this :-)

**Comment by CuzickA** [comment] 2023-11-13 14:10
Notes on pathogen genotypes

We need two pathogen genotypes
**MgAtr7 disruption** 
See Fig 1c
I would change this 
'MgAtr7(disruption)[Not assayed]' to 'MgAtr7::Hyg cassette (disruption)[Not assayed]' _(**AC**- edit now made)_
This makes the disruption labelling more consistent as noted in https://github.com/PHI-base/curation/issues/155
These disruption lines can be seen in Fig 1d gel lanes 7,8 and 9

**MgAtr7 deletion** (also referred to as 'replacement' by authors)
See Fig 1b
It could be argued that this is a partial deletion but there is no indication as to the region of the gene that was deleted. I believe the authors interchangeably call this a 'replacement' or  'deletion' strain.
For simplicity we will use
MgAtr7delta
These lines can be seen in Fig 1 d lanes 2, 3 and 6.

**Comment by CuzickA** [comment] 2023-11-13 14:16
Expts and pathogen genotypes

**fungicide sensitivity expt** 
disruption mutant

**PHI expt**
disruption mutant
deletion mutant

**Iron sensitivity expt**
disruption mutant
deletion mutant (figure names P6 , assume this corresponds to lane 6 in gel Fig1d)

**Comment by CuzickA** [comment] 2023-11-13 14:30
Checking 
![image](https://github.com/PHI-base/curation/assets/11753634/d872bf2e-fff7-49e2-8989-8446a3dac1cb)

Edits
1) delete annotation for 'MgAtr7delta' as only the disruption mutants were tested for fungicide sensitivity.
2) change the figure numbers to indicate the location of the text that this expt was reported on (eg not Fig 5).
3) Delete the more general summary in the comment section and insert copy and pasted text relevant to the annotation. This makes it easier for the person checking the curation to find the corresponding information in the publication.

Now looks like this
![image](https://github.com/PHI-base/curation/assets/11753634/33fde2b2-6e61-4508-b978-41f9611e434a)

Hi @jingluodatacurator, please look through this and my two comments about and let me know if you agree with the changes?

**Comment by CuzickA** [comment] 2023-11-13 14:47
Checking iron annotations
Currently have
![image](https://github.com/PHI-base/curation/assets/11753634/78909549-b055-481d-9ddf-de4cfac5acd2)

Change to

![image](https://github.com/PHI-base/curation/assets/11753634/2659a0f9-e378-421a-a46d-d87747ce9ee3)

Edits
1) changed comment (same reasoning as above in point 3)

Need PHIPO NTR: sensitive to iron (can cross reference to FYPO:0005825)

**_14_11_2023 update NTR now added_**
![image](https://github.com/PHI-base/curation/assets/11753634/35e45f57-0685-447b-807e-1a1dea93c45b)

**Comment by CuzickA** [comment] 2023-11-13 14:51
Added a GO MF annotation
![image](https://github.com/PHI-base/curation/assets/11753634/93c5a334-3ae8-4f65-b10f-10387a323d2c)

**Comment by CuzickA** [comment] 2023-11-13 14:56
Next steps for @jingluodatacurator for this ticket
1) please have another go at the PHI phenotype wild type metagenotype controls as noted above
2) please read through my recent comments and see if you agree with me

Next steps for myself
1) make NTR: sensitive to iron (DONE 14_11_2023)
2) check Jing's new PHI annotations once made
3) AE alteration in archetype is N/A for this session as ABC transporter so non-target site resistance
4) session will then be ready to approve.

**Comment by CuzickA** [comment] 2023-11-20 09:49
During a Teams meeting @jingluodatacurator and I talked through the PHI phenotype wild type metagenotype controls and finished off the annotations


![image](https://github.com/PHI-base/curation/assets/11753634/d61aa151-c7ea-4fe4-a2c0-a321e7457e2c)

Session now approved, closing ticket.

**Closed as completed by CuzickA** 2023-11-20 09:49 UTC
Labels: approved, chemistry, eg disruption genotype, ABC_MFS transporter
